// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/dialer/dialercontact/dialer_contact.proto

package com.android.dialer.dialercontact;

public interface DialerContactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.android.dialer.callcomposer.DialerContact)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional fixed64 photo_id = 1;</code>
   */
  boolean hasPhotoId();
  /**
   * <code>optional fixed64 photo_id = 1;</code>
   */
  long getPhotoId();

  /**
   * <code>optional string photo_uri = 2;</code>
   */
  boolean hasPhotoUri();
  /**
   * <code>optional string photo_uri = 2;</code>
   */
  String getPhotoUri();
  /**
   * <code>optional string photo_uri = 2;</code>
   */
  com.google.protobuf.ByteString
      getPhotoUriBytes();

  /**
   * <code>optional string contact_uri = 3;</code>
   */
  boolean hasContactUri();
  /**
   * <code>optional string contact_uri = 3;</code>
   */
  String getContactUri();
  /**
   * <code>optional string contact_uri = 3;</code>
   */
  com.google.protobuf.ByteString
      getContactUriBytes();

  /**
   * <code>optional string name_or_number = 4;</code>
   */
  boolean hasNameOrNumber();
  /**
   * <code>optional string name_or_number = 4;</code>
   */
  String getNameOrNumber();
  /**
   * <code>optional string name_or_number = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameOrNumberBytes();

  /**
   * <code>optional string number = 6;</code>
   */
  boolean hasNumber();
  /**
   * <code>optional string number = 6;</code>
   */
  String getNumber();
  /**
   * <code>optional string number = 6;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>optional string display_number = 7;</code>
   */
  boolean hasDisplayNumber();
  /**
   * <code>optional string display_number = 7;</code>
   */
  String getDisplayNumber();
  /**
   * <code>optional string display_number = 7;</code>
   */
  com.google.protobuf.ByteString
      getDisplayNumberBytes();

  /**
   * <code>optional string number_label = 8;</code>
   */
  boolean hasNumberLabel();
  /**
   * <code>optional string number_label = 8;</code>
   */
  String getNumberLabel();
  /**
   * <code>optional string number_label = 8;</code>
   */
  com.google.protobuf.ByteString
      getNumberLabelBytes();

  /**
   * <code>optional int32 contact_type = 9;</code>
   */
  boolean hasContactType();
  /**
   * <code>optional int32 contact_type = 9;</code>
   */
  int getContactType();

  /**
   * <code>optional .com.android.dialer.callcomposer.SimDetails sim_details = 10;</code>
   */
  boolean hasSimDetails();
  /**
   * <code>optional .com.android.dialer.callcomposer.SimDetails sim_details = 10;</code>
   */
  com.android.dialer.dialercontact.SimDetails getSimDetails();
}
